/* ============================================================
   tripdata.js  —  South America 2026
   DEFAULT_TRIP_DATA: single source of truth for the trip.
   Generated by Trip Planner on 5/21/2026, 4:36:31 PM.
   Loaded by both app.js (main page) and planner.js.
   Stops store only `nights`; dates are computed at runtime.
   ============================================================ */

const DEFAULT_TRIP_DATA =
{
  "startDate": "2026-10-23",
  "stops": [
    {
      "id": "lima",
      "city": "Lima",
      "leg": "peru",
      "emoji": "🏙️",
      "coords": [
        -12.0464,
        -77.0428
      ],
      "nights": 2,
      "accommodation": "Hostel in Miraflores (~$12–15/night)",
      "activities": [
        "Miraflores Malecón — clifftop boardwalk & paragliding over the Pacific",
        "Bohemian Barranco district — street art, peñas & pisco sours at night",
        "Larco Museum — jaw-dropping pre-Columbian gold & ceramics",
        "Mercado de Surquillo — eat the best ceviche of your life, $3",
        "Historic Centro & Plaza Mayor (UNESCO World Heritage)"
      ],
      "food": "🍽️ La Mar Cebichería — iconic Lima seafood spot in Miraflores",
      "budgetPerDay": 35,
      "transport": "🚌 Overnight Cruz del Sur bus Lima → Huaraz (~8 hrs, ~$15)"
    },
    {
      "id": "huaraz",
      "city": "Huaraz",
      "leg": "peru",
      "emoji": "🏔️",
      "coords": [
        -9.527,
        -77.5278
      ],
      "nights": 3,
      "accommodation": "Hostel in center (~$8–12/night)",
      "activities": [
        "Laguna 69 — stunning turquoise glacial lake trek (14 km round trip)",
        "Laguna Churup hike through the Cordillera Blanca wilderness",
        "Huascarán National Park — highest tropical mountain in the world",
        "Llanganuco Lakes drive — impossibly blue twin glacial lakes",
        "Hot springs at Monterrey after all that trekking 🛁"
      ],
      "food": "☕ Café Andino — beloved backpacker hangout with great coffee & pizza",
      "budgetPerDay": 28,
      "transport": "🚌 Bus Huaraz → Lima (~8 hrs), then overnight bus Lima → Ica (~4 hrs south)"
    },
    {
      "id": "ica",
      "city": "Ica / Huacachina",
      "leg": "peru",
      "emoji": "🏜️",
      "coords": [
        -14.0675,
        -75.7286
      ],
      "nights": 2,
      "accommodation": "Hostel at Huacachina oasis (~$12/night)",
      "activities": [
        "Sandboarding down MASSIVE desert dunes at sunset 🏄",
        "Dune buggy ride — full adrenaline across the Huacachina desert",
        "Swim in the Huacachina lagoon (a real desert oasis!)",
        "Nazca Lines flight by small plane (optional — ~$80–100)",
        "Pisco Bodega tour — taste Pisco where it's actually made"
      ],
      "food": "🍹 El Huacachinero — restaurant & bar right on the oasis with pisco cocktails",
      "budgetPerDay": 38,
      "transport": "🚌 Overnight bus Ica → Cusco (~16 hrs via Cruz del Sur, ~$25–35)"
    },
    {
      "id": "cusco",
      "city": "Cusco",
      "leg": "peru",
      "emoji": "🏛️",
      "coords": [
        -13.532,
        -71.9675
      ],
      "nights": 3,
      "accommodation": "Hostel in San Blas (~$10/night)",
      "activities": [
        "San Blas artisan quarter — cobblestone lanes & workshops",
        "Qorikancha — Inca Temple of the Sun beneath a colonial church",
        "Sacsayhuamán — massive Inca fortress above the city at sunset",
        "San Pedro Market — alpaca goods, exotic fruits & chicha morada",
        "Acclimatize at 3,400m with coca tea & slow city walks"
      ],
      "food": "🍴 Chicha por Gastón Acurio — Novoandina cuisine from Peru's most celebrated chef",
      "budgetPerDay": 33,
      "transport": "🚌 Shared minibus Cusco → Ollantaytambo (~2 hrs, ~$5)"
    },
    {
      "id": "ollantaytambo",
      "city": "Ollantaytambo",
      "leg": "peru",
      "emoji": "🌿",
      "coords": [
        -13.258,
        -72.2636
      ],
      "nights": 1,
      "accommodation": "Guesthouse in the village (~$15/night)",
      "activities": [
        "Climb the terraced Inca fortress at golden hour",
        "Wander the living Inca village — still inhabited after 600+ years",
        "Sacred Valley walk along the Urubamba River",
        "Pinkuylluna granary ruins — great views across the valley",
        "Board the PeruRail train to Aguas Calientes (2 hrs, ~$25–50)"
      ],
      "food": "🍝 Il Piccolo Forno — surprisingly great pasta & pizza in the Sacred Valley",
      "budgetPerDay": 30,
      "transport": "🚂 PeruRail train Ollantaytambo → Aguas Calientes (~2 hrs, ~$25–50)"
    },
    {
      "id": "aguas_calientes",
      "city": "Aguas Calientes",
      "leg": "peru",
      "emoji": "🏔️",
      "coords": [
        -13.1534,
        -72.5272
      ],
      "nights": 2,
      "accommodation": "Budget hostel in town (~$18/night)",
      "activities": [
        "MACHU PICCHU 🏔️ — wake at 4am, hike up before sunrise (skip the bus!)",
        "Huayna Picchu mountain — vertigo-inducing views above the citadel",
        "Sun Gate (Inti Punku) trek — classic panoramic Machu Picchu photo",
        "Natural hot springs soak after the big hike 🛁",
        "Night stroll of the artisan market"
      ],
      "food": "⭐ Bistro Bar Indio Feliz — highly recommended local gem, amazing trout & Peruvian fusion (local favorite!)",
      "budgetPerDay": 48,
      "transport": "🚂 Train → Cusco, overnight there; early morning transfer to Vinicunca trailhead next day"
    },
    {
      "id": "vinicunca",
      "city": "Vinicunca (Rainbow Mountain)",
      "leg": "peru",
      "emoji": "🌈",
      "coords": [
        -13.713,
        -71.3296
      ],
      "nights": 1,
      "accommodation": "Hostel back in Cusco (~$10/night)",
      "activities": [
        "Rainbow Mountain (Vinicunca) trek — mineral-striped mountain at 5,200m",
        "Watch sunrise paint the mountain in red, gold & purple hues",
        "Spot alpacas & vicuñas grazing on the high Andean plateau",
        "Optional: Red Valley (Valle Rojo) extension for fewer crowds",
        "Recovery lunch in Cusco — try cuy (roasted guinea pig) if adventurous!"
      ],
      "food": "🍸 Limo Cocina Peruana — great pisco sour & ceviches in Cusco",
      "budgetPerDay": 35,
      "transport": "✈️ Flight Cusco → Lima → Iquitos (~5 hrs total, ~$80–120)"
    },
    {
      "id": "iquitos",
      "city": "Iquitos",
      "leg": "peru",
      "emoji": "🌿",
      "coords": [
        -3.7437,
        -73.2516
      ],
      "nights": 3,
      "accommodation": "Amazon jungle lodge (~$30/night all-inclusive)",
      "activities": [
        "Amazon jungle lodge — 2 nights deep in the rainforest 🌿",
        "Piranha fishing on the Amazon River",
        "Pink river dolphins (boto) spotting — they're REAL and magical",
        "Night caiman spotting by dugout canoe 🐊",
        "Visit a local indigenous village on the river"
      ],
      "food": "🐟 Al Frio y al Fuego — floating restaurant on the Amazon River, extraordinary fresh fish",
      "budgetPerDay": 48,
      "transport": "✈️ Flight Iquitos → Manaus, Brazil (~1.5 hrs, ~$60–100)"
    },
    {
      "id": "manaus",
      "city": "Manaus",
      "leg": "brazil",
      "emoji": "🌊",
      "coords": [
        -3.119,
        -60.0217
      ],
      "nights": 3,
      "accommodation": "Hostel near Teatro Amazonas (~$15/night)",
      "activities": [
        "Meeting of the Waters — black Rio Negro meets brown Amazon without mixing 🌊",
        "Teatro Amazonas — opulent Belle Époque opera house built in the jungle",
        "Anavilhanas Archipelago boat tour through flooded forest",
        "Jungle day trip: caiman & monkey spotting + piranha fishing",
        "MUSA — world's largest submerged sculpture gallery"
      ],
      "food": "🐟 Choupana — legendary tucunaré (peacock bass) cooked in banana leaf",
      "budgetPerDay": 40,
      "transport": "✈️ Flight Manaus → Salvador, Bahia (~4 hrs, ~$50–80)"
    },
    {
      "id": "salvador",
      "city": "Salvador",
      "leg": "brazil",
      "emoji": "🎭",
      "coords": [
        -12.9714,
        -38.5014
      ],
      "nights": 5,
      "accommodation": "Hostel in Pelourinho (~$12/night)",
      "activities": [
        "Pelourinho — UNESCO-listed historic center, colorful colonial architecture",
        "Live Capoeira performances in the streets of Pelô 🥋",
        "Afro-Brazilian culture: Candomblé ceremony (respectful visit)",
        "Praia do Porto da Barra — turquoise water in a stunning bay 🏖️",
        "Mercado Modelo — crafts, live music & a cold Brahma beer"
      ],
      "food": "🍧 Sorveteria da Ribeira — legendary açaí na tigela & tropical ice cream",
      "budgetPerDay": 38,
      "transport": "🚌 Shared bus Salvador → Arraial d'Ajuda (~8 hrs + ferry, ~$20)"
    },
    {
      "id": "arraial",
      "city": "Arraial d'Ajuda",
      "leg": "brazil",
      "emoji": "🏖️",
      "coords": [
        -16.4792,
        -39.0631
      ],
      "nights": 4,
      "accommodation": "Pousada near the village (~$20/night)",
      "activities": [
        "Praia do Mucugê — stunning cliff-backed beach with crystal clear water 🏖️",
        "Quadrante beach bar — daytime vibes, caipirinhas & live music",
        "Dune buggy rental along the beautiful Bahia coastline",
        "Kayak the natural reef pools at Praia do Rio da Barra",
        "Sunset at the Mirante clifftop viewpoint over the Atlantic"
      ],
      "food": "🦞 Restaurante do Bosque — fresh seafood moqueca (coconut fish stew), unmissable",
      "budgetPerDay": 43,
      "transport": "🚌 Overnight bus Arraial d'Ajuda → Rio de Janeiro (~12 hrs, ~$30)"
    },
    {
      "id": "rio",
      "city": "Rio de Janeiro",
      "leg": "brazil",
      "emoji": "🌴",
      "coords": [
        -22.9068,
        -43.1729
      ],
      "nights": 7,
      "accommodation": "Hostel in Santa Teresa or Botafogo (~$15/night)",
      "activities": [
        "Christ the Redeemer at sunrise — arrive by 7am to beat the clouds & crowds",
        "Sugarloaf Mountain cable car — sunset views over the bay 🌅",
        "Samba night in Lapa — Pedra do Sal on Mondays is free & authentic 🎶",
        "Surf lesson at Prainha or Recreio beach 🏄",
        "Tijuca National Park — hiking in an urban Atlantic rainforest"
      ],
      "food": "☕ Confeitaria Colombo — 1894 Belle Époque café, try the coconut tart",
      "budgetPerDay": 53,
      "transport": "🚌 Overnight bus or ✈️ flight Rio → Foz do Iguaçu (~20 hrs bus OR 2 hr flight)"
    },
    {
      "id": "iguazu",
      "city": "Foz do Iguaçu",
      "leg": "brazil",
      "emoji": "💧",
      "coords": [
        -25.5478,
        -54.5882
      ],
      "nights": 4,
      "accommodation": "Hostel in Foz (~$12/night)",
      "activities": [
        "Iguazu Falls (Brazilian side) — panoramic walkways ABOVE the falls 💧",
        "Iguazu Falls (Argentine side, day trip) — walk catwalks INTO the falls",
        "Devil's Throat (Garganta del Diablo) — most powerful waterfall on Earth 🌊",
        "Parque das Aves — toucans, macaws & parrots at arm's length 🦜",
        "Moonlit falls visit if scheduled (magical every full moon)"
      ],
      "food": "🥩 Bufalo Branco — legendary all-you-can-eat Brazilian churrascaria",
      "budgetPerDay": 45,
      "transport": "✈️ Flight Foz → El Calafate (via Buenos Aires, ~5 hrs total)"
    },
    {
      "id": "el_calafate",
      "city": "El Calafate",
      "leg": "argentina",
      "emoji": "🧊",
      "coords": [
        -50.3397,
        -72.2656
      ],
      "nights": 4,
      "accommodation": "Hostel in town (~$18/night)",
      "activities": [
        "Perito Moreno Glacier — walk catwalks as HUGE ice chunks calve into the lake 🧊",
        "Mini-trekking on the glacier with crampons — life-changing experience",
        "Boat safari under towering glacier walls — you'll feel tiny",
        "Laguna Nimez — flamingos on a lake literally in town 🦩",
        "Sunset from the Mirador del Glaciar lookout"
      ],
      "food": "🐑 La Tablita — legendary Patagonian lamb asado, best in El Calafate",
      "budgetPerDay": 55,
      "transport": "🚌 Bus El Calafate → El Chaltén (~3 hrs, ~$10)"
    },
    {
      "id": "el_chalten",
      "city": "El Chaltén",
      "leg": "argentina",
      "emoji": "⛰️",
      "coords": [
        -49.3311,
        -72.886
      ],
      "nights": 3,
      "accommodation": "Hostel / refugio (~$18/night)",
      "activities": [
        "Laguna de los Tres — epic Fitz Roy viewpoint trek (24 km — do it!!) ⛰️",
        "Laguna Torre — Cerro Torre spire reflection at sunrise",
        "Chorrillo del Salto waterfall (easy, 1 hr from town)",
        "Via Ferrata or guided rock climbing with local outfitters",
        "Craft beer at El Chaltén Micro-Cervecería — best beers in Patagonia 🍺"
      ],
      "food": "🍲 Patagónico Restaurant — hearty Patagonian lamb stew & ember-roasted lamb chops",
      "budgetPerDay": 50,
      "transport": "🚌 Bus El Chaltén → El Calafate, then ✈️ fly north to Bariloche (~2 hr flight)"
    },
    {
      "id": "bariloche",
      "city": "Bariloche",
      "leg": "argentina",
      "emoji": "🍫",
      "coords": [
        -41.1335,
        -71.3103
      ],
      "nights": 5,
      "accommodation": "Hostel near Centro (~$15/night)",
      "activities": [
        "Cerro Campanario chairlift — Patagonia's most iconic lake panorama 🏔️",
        "Circuit Chico — bike or drive around turquoise Nahuel Huapi Lake",
        "Cerro Tronador day trip — hike to the \"exploding mountain\" black glacier",
        "Chocolate shop hopping — Bariloche is Argentina's chocolate capital 🍫",
        "Kayak on Lago Nahuel Huapi with snowy Andean peaks all around"
      ],
      "food": "🍦 Jauja Heladería — Argentina's best artisanal ice cream, try calafate berry flavor",
      "budgetPerDay": 50,
      "transport": "✈️ Flight Bariloche → Mendoza (~1.5 hrs, ~$40–70)"
    },
    {
      "id": "mendoza",
      "city": "Mendoza",
      "leg": "argentina",
      "emoji": "🍷",
      "coords": [
        -32.8908,
        -68.8272
      ],
      "nights": 3,
      "accommodation": "Hostel in Godoy Cruz (~$14/night)",
      "activities": [
        "Luján de Cuyo & Maipú wine tour — RENT A BIKE between bodegas 🚲🍷",
        "Aconcagua viewpoint day trip — highest peak in the Americas (6,961m) 🏔️",
        "Mendoza River rafting or kayaking for adventure 🚣",
        "Olive oil & artisanal cheese tasting route",
        "Parque General San Martín evening walk & sunset"
      ],
      "food": "🥩 Francesco Bistró — world-class Malbec paired with locally-raised steak",
      "budgetPerDay": 53,
      "transport": "✈️ Flight Mendoza → Corrientes (~2 hrs, ~$40–60) or overnight bus"
    },
    {
      "id": "corrientes",
      "city": "Corrientes",
      "leg": "argentina",
      "emoji": "🦦",
      "coords": [
        -27.4806,
        -58.8341
      ],
      "nights": 3,
      "accommodation": "Hostel / estancia (~$12/night)",
      "activities": [
        "Iberá Wetlands — one of South America's greatest wildlife sanctuaries 🌿",
        "Capybara spotting — they literally walk around campsites 🦦",
        "Caiman & marsh deer boat safari at dusk 🐊",
        "350+ bird species — jabiru storks, roseate spoonbills, kingfishers 🐦",
        "Sunset cruise on the Paraná River with a cold Quilmes"
      ],
      "food": "🔥 Parador Iberá — asado with capybara watching from your picnic table",
      "budgetPerDay": 43,
      "transport": "🚌 Bus or ✈️ flight Corrientes → Buenos Aires (~8 hr bus or 1 hr flight)"
    },
    {
      "id": "buenos_aires",
      "city": "Buenos Aires",
      "leg": "argentina",
      "emoji": "🥩",
      "coords": [
        -34.6037,
        -58.3816
      ],
      "nights": 13,
      "accommodation": "With family / Airbnb in Palermo (~free–$25/night)",
      "activities": [
        "La Boca & Caminito — street tango, colorful houses & street food 💃",
        "San Telmo Sunday market — antiques, empanadas & live tango on the street",
        "Midnight tango at Milonga Canning — authentic, electric, not touristy 🎶",
        "🎄 NAVIDAD with family — asado, dulce de leche pasteles & midnight fireworks",
        "🎆 NEW YEAR'S EVE in BA — biggest street party, fireworks over Río de la Plata!"
      ],
      "food": "🥩 Don Julio Parrilla — the #1 steakhouse in Buenos Aires (book 2 weeks ahead)",
      "budgetPerDay": 45,
      "transport": "✈️ International flight home from Ezeiza (EZE) airport 🏡"
    }
  ],
  "friends": [
    {
      "id": "f1",
      "name": "Marco",
      "legs": "Peru",
      "dates": "Oct 26 – Nov 5",
      "color": "#6bcb77",
      "note": "Meeting in Cusco, comes for Machu Picchu & Rainbow Mountain"
    },
    {
      "id": "f2",
      "name": "Lucia",
      "legs": "Brazil",
      "dates": "Nov 17 – Nov 30",
      "color": "#ffd93d",
      "note": "Joins in Rio – local contact knows great samba clubs!"
    },
    {
      "id": "f3",
      "name": "Diego",
      "legs": "Argentina",
      "dates": "Dec 1 – Jan 2",
      "color": "#4d96ff",
      "note": "Full Argentina leg – Patagonian trekking buddy & Buenos Aires family friend"
    }
  ]
};